name: config

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  pull_request:

jobs:
  Login:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: "pip"
      - name: install  packages
        run: pip install -r src/requirements.txt
      - name: change directory
        run: cd src
      - name: generate profile
        run: echo '{"pdc_username":"${{secrets.pdc_username}}","pdc_password":"${{secrets.pdc_password}}","email_address":"${{secrets.email_address}}","email_address":"${{secrets.email_authcode}}"}' > profile.json
      - name: execute script
        run: python -B health.py
